# Generated by Django 2.2.9 on 2020-05-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('spotify_id', models.CharField(max_length=128)),
                ('album_uri', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('spotify_id', models.CharField(max_length=128)),
                ('artist_uri', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('spotify_id', models.CharField(max_length=128)),
                ('track_uri', models.CharField(max_length=128)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Artist'),
        ),
    ]
