# Generated by Django 2.2.9 on 2020-05-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200521_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_image',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
