# Generated by Django 2.2.9 on 2020-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_track_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='acousticness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='danceability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='instrumentalness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='liveness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='loudness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='speechiness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='tempo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='valence',
            field=models.FloatField(default=0.0),
        ),
    ]
