# Generated by Django 2.2.9 on 2020-05-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_spotify_id',
            new_name='track_id',
        ),
    ]
