# Generated by Django 2.2.9 on 2020-05-26 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='favourites',
            field=models.ManyToManyField(default='none', related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
