# Generated by Django 2.2.9 on 2020-05-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_track_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
