# Generated by Django 2.2.9 on 2020-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rating_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
